spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1021
    url: jdbc:mysql:///shop_backuser

dubbo:
  registry:
    address: zookeeper://192.168.177.211:2181
  application:
    name: back_service
  protocol:
    port: -1
    name: dubbo

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml